---
title: "BEC site series near Savona (Eagle Hills)"
author: "Danielle Lafleur, Cristhina Florez, Catalina Valle, Andrea Patino"
format: html
editor: visual
---

Packages

```{r}
library(tidyverse)
library(mlr3)
library(sf)
library(terra)
library(lidR)
library(Rsagacmd)
library(mapview)
library(units)
library(bcmaps)
```

Download provided LAS data and relevant GeoPackage layers.

```{r}

las_ctg <- readLAScatalog("Eagle Hills_IDFdk1.las", filter = "-keep_random_fraction 0.5")
las_ctg
plot(las_ctg, mapview = TRUE)

site_ctg <- st_as_sf(las_ctg, coords = c("Long", "Lat"), crs = 3005)
site_ctg

bec_ctg <- bec() %>% 
  st_intersection(site_ctg)

opt_output_files(las_ctg) <- "01_retile/{XLEFT}_{YBOTTOM}"

opt_chunk_size(las_ctg) <- 500
opt_chunk_buffer(las_ctg) <- 0

opt_chunk_alignment(las_ctg) <- c(500, 500)
plot(las_ctg, chunk_pattern = TRUE)

ctg_tiled <- catalog_retile(las_ctg)

View(ctg_tiled)
plot(ctg_tiled, mapview = TRUE)

opt_filter(ctg_tiled) <- ""

opt_chunk_size(ctg_tiled) <- 0
opt_chunk_buffer(ctg_tiled) <- 15

opt_output_files(ctg_tiled) <- "02_ground/{*}"

ctg_ground <- classify_ground(ctg_tiled, algorithm = csf(sloop_smooth = TRUE))

opt_output_files(ctg_ground) <- ""
dem <- rasterize_terrain(ctg_ground, res = 1, algorithm = tin())

dir.create("ta", showWarnings = FALSE)
dem <- writeRaster(dem, "ta/dem.tif", overwrite = TRUE)
```
